{
 "title": "Oxia - Cluster Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Oxia Cluster",
    "query": {
     "query": "label_values(oxia_coordinator_node_running, oxia_cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "oxia_server_wal_entries{oxia_cluster=~\"$cluster\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Servers health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Healthy Server Pods",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(oxia_coordinator_node_running) / sum(oxia_coordinator_node_running)",
     "legendFormat": "{{oxia_namespace}}-{{shard}} - {{pod}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Write ops/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(\n      rate(oxia_server_db_puts_total{oxia_cluster=~\"$cluster\",  oxia_namespace=~\"$namespace\"}[1m])\n    + rate(oxia_server_db_gets_total{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\"}[1m])\n    + rate(oxia_server_db_lists_total{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\"}[1m])\n    + rate(oxia_server_db_deletes_total{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\"}[1m])\n    + rate(oxia_server_db_delete_ranges_total{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\",}[1m])\n) by (oxia_namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Read ops/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(oxia_server_db_gets_total{ oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\"}[1m])\n  + rate(oxia_server_db_lists_total{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\"}[1m])\n) by (oxia_namespace)\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Ops Latency (50pct)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le, oxia_namespace) \n(oxia_server_leader_write_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Ops Latency (99pct)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, oxia_namespace) \n(oxia_server_leader_write_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Ops Latency (99.9pct)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum by (le, oxia_namespace) \n(oxia_server_leader_write_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Ops Latency (Max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(1.0, sum by (le, oxia_namespace) \n(oxia_server_leader_write_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB size on disk",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(oxia_server_kv_pebble_disk_space_bytes{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\"}) by (oxia_namespace)\n\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}