{
 "title": "Oxia - gRPC",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Oxia Cluster",
    "query": {
     "query": "label_values(oxia_coordinator_node_running, oxia_cluster)"
    }
   },
   {
    "name": "component",
    "label": "Component",
    "query": {
     "query": "grpc_server_handled_total{oxia_cluster=~\"$cluster\"}"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "grpc_server_handled_total{oxia_cluster=~\"$cluster\", job=~\"$component\"}"
    }
   },
   {
    "name": "grpc_service",
    "label": "gRPC Service",
    "query": {
     "query": "grpc_server_handled_total{oxia_cluster=~\"$cluster\", job=~\"$component\"}"
    }
   },
   {
    "name": "grpc_method",
    "label": "gRPC Method",
    "query": {
     "query": "grpc_server_handled_total{oxia_cluster=~\"$cluster\", job=~\"$component\", grpc_service=~\"$grpc_service\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pod -  $pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pod" },
  {
   "title": "gRPC Server - Completed requests /s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(grpc_server_handled_total{\n        oxia_cluster=~\"$cluster\", pod=~\"$pod\", grpc_service=~\"$grpc_service\", grpc_method=~\"$grpc_method\"\n    }[1m])) \n\nby (grpc_service, grpc_method)\n\n\n",
     "legendFormat": "{{grpc_service}} - {{grpc_method}}"
    }
   ]
  },
  {
   "title": "gRPC Server - Failed requests /s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(\n    rate(grpc_server_handled_total{\n        oxia_cluster=~\"$cluster\", pod=~\"$pod\", grpc_service=~\"$grpc_service\", grpc_method=~\"$grpc_method\", grpc_code!=\"OK\"\n    }[1m])) \n\nby (grpc_service, grpc_method, grpc_code) > 0\n\n\n",
     "legendFormat": "{{grpc_method}} - {{ grpc_code }}"
    }
   ]
  },
  {
   "title": "gRPC Server - Msgs sent/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(grpc_server_msg_sent_total{\n        oxia_cluster=~\"$cluster\", pod=~\"$pod\", grpc_service=~\"$grpc_service\", grpc_method=~\"$grpc_method\"\n    }[1m])\n) \nby (grpc_service, grpc_method)\n\n\n",
     "legendFormat": "{{grpc_service}} - {{grpc_method}}"
    }
   ]
  },
  {
   "title": "gRPC Server - Msgs received/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(\n    rate(grpc_server_msg_received_total{\n        oxia_cluster=~\"$cluster\", pod=~\"$pod\", grpc_service=~\"$grpc_service\", grpc_method=~\"$grpc_method\"\n    }[1m])) \n\nby (grpc_service, grpc_method)\n\n\n",
     "legendFormat": "{{grpc_service}} - {{grpc_method}}"
    }
   ]
  },
  {
   "title": "gRPC Client - Completed requests /s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(grpc_client_handled_total{\n        oxia_cluster=~\"$cluster\", pod=~\"$pod\", grpc_service=~\"$grpc_service\", grpc_method=~\"$grpc_method\", grpc_code=\"OK\"\n    }[1m])) \n\nby (grpc_service, grpc_method)\n\n\n",
     "legendFormat": "{{grpc_service}} - {{grpc_method}}"
    }
   ]
  },
  {
   "title": "gRPC Client - Failed requests /s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(\n    rate(grpc_server_client_total{\n        oxia_cluster=~\"$cluster\", pod=~\"$pod\", grpc_service=~\"$grpc_service\", grpc_method=~\"$grpc_method\", grpc_code!=\"OK\"\n    }[1m])) \n\nby (grpc_service, grpc_method, grpc_code) > 0\n\n\n",
     "legendFormat": "{{grpc_method}} - {{ grpc_code }}"
    }
   ]
  },
  {
   "title": "gRPC Client - Msgs sent/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(grpc_client_msg_sent_total{\n        oxia_cluster=~\"$cluster\", pod=~\"$pod\", grpc_service=~\"$grpc_service\", grpc_method=~\"$grpc_method\"\n    }[1m])\n) \nby (grpc_service, grpc_method)\n\n\n",
     "legendFormat": "{{grpc_service}} - {{grpc_method}}"
    }
   ]
  },
  {
   "title": "gRPC Client - Msgs received/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(\n    rate(grpc_client_msg_received_total{\n        oxia_cluster=~\"$cluster\", pod=~\"$pod\", grpc_service=~\"$grpc_service\", grpc_method=~\"$grpc_method\"\n    }[1m])) \n\nby (grpc_service, grpc_method)\n\n\n",
     "legendFormat": "{{grpc_service}} - {{grpc_method}}"
    }
   ]
  }
 ]
}