// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/internal.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InternalEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InternalEmpty) Reset() {
	*x = InternalEmpty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_internal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InternalEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalEmpty) ProtoMessage() {}

func (x *InternalEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalEmpty.ProtoReflect.Descriptor instead.
func (*InternalEmpty) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{0}
}

type LogEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Epoch            uint64 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	EntryId          uint64 `protobuf:"varint,2,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	LastAddConfirmed int64  `protobuf:"varint,3,opt,name=last_add_confirmed,json=lastAddConfirmed,proto3" json:"last_add_confirmed,omitempty"`
	Payload          []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_internal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{1}
}

func (x *LogEntry) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *LogEntry) GetEntryId() uint64 {
	if x != nil {
		return x.EntryId
	}
	return 0
}

func (x *LogEntry) GetLastAddConfirmed() int64 {
	if x != nil {
		return x.LastAddConfirmed
	}
	return 0
}

func (x *LogEntry) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ReadLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shard        uint32 `protobuf:"varint,1,opt,name=shard,proto3" json:"shard,omitempty"`
	FirstEntryId uint64 `protobuf:"varint,2,opt,name=first_entry_id,json=firstEntryId,proto3" json:"first_entry_id,omitempty"`
}

func (x *ReadLogRequest) Reset() {
	*x = ReadLogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_internal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadLogRequest) ProtoMessage() {}

func (x *ReadLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadLogRequest.ProtoReflect.Descriptor instead.
func (*ReadLogRequest) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{2}
}

func (x *ReadLogRequest) GetShard() uint32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

func (x *ReadLogRequest) GetFirstEntryId() uint64 {
	if x != nil {
		return x.FirstEntryId
	}
	return 0
}

type ConfirmedEntryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shard    uint32 `protobuf:"varint,1,opt,name=shard,proto3" json:"shard,omitempty"`
	Follower string `protobuf:"bytes,2,opt,name=follower,proto3" json:"follower,omitempty"`
	Epoch    uint64 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	EntryId  uint64 `protobuf:"varint,4,opt,name=entryId,proto3" json:"entryId,omitempty"`
}

func (x *ConfirmedEntryRequest) Reset() {
	*x = ConfirmedEntryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_internal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmedEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmedEntryRequest) ProtoMessage() {}

func (x *ConfirmedEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmedEntryRequest.ProtoReflect.Descriptor instead.
func (*ConfirmedEntryRequest) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmedEntryRequest) GetShard() uint32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

func (x *ConfirmedEntryRequest) GetFollower() string {
	if x != nil {
		return x.Follower
	}
	return ""
}

func (x *ConfirmedEntryRequest) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ConfirmedEntryRequest) GetEntryId() uint64 {
	if x != nil {
		return x.EntryId
	}
	return 0
}

type FenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shard uint32 `protobuf:"varint,1,opt,name=shard,proto3" json:"shard,omitempty"`
	Epoch uint64 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
}

func (x *FenceRequest) Reset() {
	*x = FenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_internal_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FenceRequest) ProtoMessage() {}

func (x *FenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FenceRequest.ProtoReflect.Descriptor instead.
func (*FenceRequest) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{4}
}

func (x *FenceRequest) GetShard() uint32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

func (x *FenceRequest) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type FenceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastEntry int64 `protobuf:"varint,2,opt,name=last_entry,json=lastEntry,proto3" json:"last_entry,omitempty"`
}

func (x *FenceResponse) Reset() {
	*x = FenceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_internal_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FenceResponse) ProtoMessage() {}

func (x *FenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FenceResponse.ProtoReflect.Descriptor instead.
func (*FenceResponse) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{5}
}

func (x *FenceResponse) GetLastEntry() int64 {
	if x != nil {
		return x.LastEntry
	}
	return 0
}

type ClusterStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShardsStatus      []*ShardStatus `protobuf:"bytes,1,rep,name=shards_status,json=shardsStatus,proto3" json:"shards_status,omitempty"`
	ReplicationFactor uint32         `protobuf:"varint,2,opt,name=replication_factor,json=replicationFactor,proto3" json:"replication_factor,omitempty"`
}

func (x *ClusterStatus) Reset() {
	*x = ClusterStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_internal_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatus) ProtoMessage() {}

func (x *ClusterStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatus.ProtoReflect.Descriptor instead.
func (*ClusterStatus) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{6}
}

func (x *ClusterStatus) GetShardsStatus() []*ShardStatus {
	if x != nil {
		return x.ShardsStatus
	}
	return nil
}

func (x *ClusterStatus) GetReplicationFactor() uint32 {
	if x != nil {
		return x.ReplicationFactor
	}
	return 0
}

type ShardStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shard     uint32           `protobuf:"varint,1,opt,name=shard,proto3" json:"shard,omitempty"`
	Leader    *ServerAddress   `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	Followers []*ServerAddress `protobuf:"bytes,3,rep,name=followers,proto3" json:"followers,omitempty"`
	Epochs    []*EpochStatus   `protobuf:"bytes,4,rep,name=epochs,proto3" json:"epochs,omitempty"`
}

func (x *ShardStatus) Reset() {
	*x = ShardStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_internal_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardStatus) ProtoMessage() {}

func (x *ShardStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardStatus.ProtoReflect.Descriptor instead.
func (*ShardStatus) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{7}
}

func (x *ShardStatus) GetShard() uint32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

func (x *ShardStatus) GetLeader() *ServerAddress {
	if x != nil {
		return x.Leader
	}
	return nil
}

func (x *ShardStatus) GetFollowers() []*ServerAddress {
	if x != nil {
		return x.Followers
	}
	return nil
}

func (x *ShardStatus) GetEpochs() []*EpochStatus {
	if x != nil {
		return x.Epochs
	}
	return nil
}

type EpochStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Epoch      uint64 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	FirstEntry uint64 `protobuf:"varint,2,opt,name=first_entry,json=firstEntry,proto3" json:"first_entry,omitempty"`
}

func (x *EpochStatus) Reset() {
	*x = EpochStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_internal_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EpochStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochStatus) ProtoMessage() {}

func (x *EpochStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochStatus.ProtoReflect.Descriptor instead.
func (*EpochStatus) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{8}
}

func (x *EpochStatus) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *EpochStatus) GetFirstEntry() uint64 {
	if x != nil {
		return x.FirstEntry
	}
	return 0
}

type ServerAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InternalUrl string `protobuf:"bytes,1,opt,name=internal_url,json=internalUrl,proto3" json:"internal_url,omitempty"`
	PublicUrl   string `protobuf:"bytes,2,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
}

func (x *ServerAddress) Reset() {
	*x = ServerAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_internal_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerAddress) ProtoMessage() {}

func (x *ServerAddress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerAddress.ProtoReflect.Descriptor instead.
func (*ServerAddress) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{9}
}

func (x *ServerAddress) GetInternalUrl() string {
	if x != nil {
		return x.InternalUrl
	}
	return ""
}

func (x *ServerAddress) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

var File_proto_internal_proto protoreflect.FileDescriptor

var file_proto_internal_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0f, 0x0a,
	0x0d, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x83,
	0x01, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x70, 0x6f, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63,
	0x68, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x12,
	0x6c, 0x61, 0x73, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x41, 0x64,
	0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x22, 0x4c, 0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64, 0x4c, 0x6f, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x12, 0x24, 0x0a, 0x0e,
	0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x66, 0x69, 0x72, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x49, 0x64, 0x22, 0x79, 0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x68, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x68, 0x61, 0x72,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x65, 0x70,
	0x6f, 0x63, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x64, 0x22, 0x3a, 0x0a,
	0x0c, 0x46, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x68,
	0x61, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x22, 0x2e, 0x0a, 0x0d, 0x46, 0x65, 0x6e,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x6c, 0x61, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x77, 0x0a, 0x0d, 0x43, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x37, 0x0a, 0x0d, 0x73, 0x68,
	0x61, 0x72, 0x64, 0x73, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0c, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x2d, 0x0a, 0x12, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x11, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x22, 0xb1, 0x01, 0x0a, 0x0b, 0x53, 0x68, 0x61, 0x72, 0x64, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x12, 0x2c, 0x0a, 0x06, 0x6c, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x06,
	0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x32, 0x0a, 0x09, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52,
	0x09, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x12, 0x2a, 0x0a, 0x06, 0x65, 0x70,
	0x6f, 0x63, 0x68, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x65, 0x70, 0x6f, 0x63, 0x68, 0x73, 0x22, 0x44, 0x0a, 0x0b, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x66,
	0x69, 0x72, 0x73, 0x74, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x51, 0x0a, 0x0d,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x21, 0x0a,
	0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x55, 0x72, 0x6c,
	0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x55, 0x72, 0x6c, 0x32,
	0x8a, 0x01, 0x0a, 0x0b, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x41, 0x50, 0x49, 0x12,
	0x3c, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3d, 0x0a,
	0x06, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f,
	0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x24, 0x5a, 0x22,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x2f, 0x6f, 0x78, 0x69, 0x61, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_internal_proto_rawDescOnce sync.Once
	file_proto_internal_proto_rawDescData = file_proto_internal_proto_rawDesc
)

func file_proto_internal_proto_rawDescGZIP() []byte {
	file_proto_internal_proto_rawDescOnce.Do(func() {
		file_proto_internal_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_internal_proto_rawDescData)
	})
	return file_proto_internal_proto_rawDescData
}

var file_proto_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_internal_proto_goTypes = []interface{}{
	(*InternalEmpty)(nil),         // 0: proto.InternalEmpty
	(*LogEntry)(nil),              // 1: proto.LogEntry
	(*ReadLogRequest)(nil),        // 2: proto.ReadLogRequest
	(*ConfirmedEntryRequest)(nil), // 3: proto.ConfirmedEntryRequest
	(*FenceRequest)(nil),          // 4: proto.FenceRequest
	(*FenceResponse)(nil),         // 5: proto.FenceResponse
	(*ClusterStatus)(nil),         // 6: proto.ClusterStatus
	(*ShardStatus)(nil),           // 7: proto.ShardStatus
	(*EpochStatus)(nil),           // 8: proto.EpochStatus
	(*ServerAddress)(nil),         // 9: proto.ServerAddress
}
var file_proto_internal_proto_depIdxs = []int32{
	7, // 0: proto.ClusterStatus.shards_status:type_name -> proto.ShardStatus
	9, // 1: proto.ShardStatus.leader:type_name -> proto.ServerAddress
	9, // 2: proto.ShardStatus.followers:type_name -> proto.ServerAddress
	8, // 3: proto.ShardStatus.epochs:type_name -> proto.EpochStatus
	6, // 4: proto.InternalAPI.UpdateStatus:input_type -> proto.ClusterStatus
	3, // 5: proto.InternalAPI.Follow:input_type -> proto.ConfirmedEntryRequest
	0, // 6: proto.InternalAPI.UpdateStatus:output_type -> proto.InternalEmpty
	1, // 7: proto.InternalAPI.Follow:output_type -> proto.LogEntry
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_internal_proto_init() }
func file_proto_internal_proto_init() {
	if File_proto_internal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_internal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InternalEmpty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_internal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_internal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadLogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_internal_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmedEntryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_internal_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_internal_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FenceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_internal_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_internal_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_internal_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EpochStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_internal_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_internal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_internal_proto_goTypes,
		DependencyIndexes: file_proto_internal_proto_depIdxs,
		MessageInfos:      file_proto_internal_proto_msgTypes,
	}.Build()
	File_proto_internal_proto = out.File
	file_proto_internal_proto_rawDesc = nil
	file_proto_internal_proto_goTypes = nil
	file_proto_internal_proto_depIdxs = nil
}
